package software;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * @author Jhonatan Romero
 */
public class Menu extends javax.swing.JFrame {

    public static int valmus = 0;
    Fuentes tipoFuente;

    public Menu() {

        initComponents();
        tipoFuente = new Fuentes();
        this.setLocationRelativeTo(null);
        this.setSize(760, 480);
        Titulo.setFont(tipoFuente.fuente(tipoFuente.positive, 0, 48));
        encriptar1.setFont(tipoFuente.fuente(tipoFuente.positive, 0, 32));
        decifrar.setFont(tipoFuente.fuente(tipoFuente.positive, 0, 32));
        salir.setFont(tipoFuente.fuente(tipoFuente.positive, 0, 24));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        decifrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        encriptar1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        barrasup = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 480));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(2, 43, 52));
        salir.setFont(new java.awt.Font("Positive System", 0, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(51, 153, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setOpaque(true);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 50, 40));

        decifrar.setFont(new java.awt.Font("Positive System", 0, 32)); // NOI18N
        decifrar.setForeground(new java.awt.Color(204, 204, 255));
        decifrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        decifrar.setText("$\"\"\"\"");
        decifrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decifrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decifrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decifrarMouseExited(evt);
            }
        });
        jPanel1.add(decifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 260, 70));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        encriptar1.setFont(new java.awt.Font("Positive System", 0, 32)); // NOI18N
        encriptar1.setForeground(new java.awt.Color(153, 255, 255));
        encriptar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encriptar1.setText(":::::");
        encriptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encriptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encriptar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encriptar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encriptar1MouseExited(evt);
            }
        });
        jPanel1.add(encriptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 260, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marco.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        Titulo.setFont(new java.awt.Font("Positive System", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(102, 153, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("?¡\"#&/(!\"?¡");
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
        });
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 760, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marco.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Blue Futuristic Technology Pitch Deck Presentation.png"))); // NOI18N
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fondoMouseEntered(evt);
            }
        });
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        barrasup.setBackground(new java.awt.Color(204, 204, 204));
        barrasup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barrasupMouseDragged(evt);
            }
        });
        barrasup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barrasupMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barrasupLayout = new javax.swing.GroupLayout(barrasup);
        barrasup.setLayout(barrasupLayout);
        barrasupLayout.setHorizontalGroup(
            barrasupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        barrasupLayout.setVerticalGroup(
            barrasupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(barrasup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decifrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decifrarMouseEntered
        decifrar.setForeground(new Color(153, 153, 153));
        decifrar.setText("DECIFRAR");
    }//GEN-LAST:event_decifrarMouseEntered
    int x, y;
    private void barrasupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barrasupMouseDragged
        int Xmouse = evt.getXOnScreen();
        int Ymouse = evt.getYOnScreen();
        this.setLocation(Xmouse - x, Ymouse - y);
    }//GEN-LAST:event_barrasupMouseDragged

    private void barrasupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barrasupMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_barrasupMousePressed

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setForeground(Color.red);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setForeground(new Color(51, 153, 255));

    }//GEN-LAST:event_salirMouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void decifrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decifrarMouseExited
        decifrar.setForeground(new Color(204, 204, 255));
    }//GEN-LAST:event_decifrarMouseExited

    private void decifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decifrarMouseClicked
        Descifrar mostrar = new Descifrar();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_decifrarMouseClicked

    private void encriptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encriptar1MouseClicked
        Encriptar mostrar = new Encriptar();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_encriptar1MouseClicked

    private void encriptar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encriptar1MouseEntered
        encriptar1.setForeground(new Color(153, 153, 153));
        encriptar1.setText("ENCRIPTAR");
    }//GEN-LAST:event_encriptar1MouseEntered

    private void encriptar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encriptar1MouseExited
        encriptar1.setForeground(new Color(153, 255, 255));
        //encriptar1.setText("encriptar");
    }//GEN-LAST:event_encriptar1MouseExited

    private void fondoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseEntered

        try {
            if (valmus == 0) {
                Music.RunMusic("src/Msc/Spy0.wav");
                
            }
            valmus++;

        } catch (LineUnavailableException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_fondoMouseEntered

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        Titulo.setForeground(new Color(102,153,255));
        Titulo.setText("CRIPTO CODE");
    }//GEN-LAST:event_TituloMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel barrasup;
    private javax.swing.JLabel decifrar;
    private javax.swing.JLabel encriptar1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
